apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wdqjel1n5-python 
  janus-idp.io/tekton: wdqjel1n5-python
  backstage.io/kubernetes-id: wdqjel1n5-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wdqjel1n5-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml